[package]
name = "raspi-oled"
version = "0.1.0"
authors = ["chux0519 <chuxdesign@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.6.0-alpha.2"
linux-embedded-hal = "0.2.2"
machine-ip = "0.2.1"
ssd1306 = "0.3.0-alpha.2"
